meta:
  engine: 4.0.5
  name: ouleetka
  version: 0.1
  ref: "ouleetka v0.1"
  author: nxtk
  url: https://github.com/nxtk/ouleetka

  footprints:
    #template: &kicad_template "kicad5"
    template: &kicad_template "kicad8_1"
    key_switch: &fp_key_switch ceoloide/switch_choc_v1_v2
    reset_switch: &fp_reset_switch "ceoloide/reset_switch_smd_side"
    power_switch: &fp_power_switch "ceoloide/power_switch_smd_side"
    mounting_hole: &fp_mounting_hole "ceoloide/mounting_hole"
    mcu: &fp_mcu "ceoloide/mcu_nice_nano"
    display_nicenano: &fp_display_niceview "ceoloide/display_nice_view"
    display_oled: &fp_display_oled "ceoloide/display_ssd1306"
    battery_connector: &fp_battery_connector "ceoloide/battery_connector_jst_ph_2"
    diode: &fp_diode "ceoloide/diode_tht_sod123"

units:
  $default_autobind: 0
  tolerance_small: 0.15
  tolerance_medium: 0.25
  tolerance_high: 0.5

  u: 17
  U: 17
  kx: 17 # spacing between key centers (X-axis)
  ky: 17 # spacing between key centers (Y-axis)
  kco: 13.8 # key cutout hole width (cherry, choc v2: 14, choc v1: 13.8)
  kch: 16.5 # keycap height (cherry: 18, choc: 16.5, choc CFX 16.5)
  kcw: 16.5 # keycap width (cherry: 18, choc: 17.5, choc CFX 16.5)

  led_pos_x: 0 # Led X position relative to the switch center
  led_pos_y: 4.7 # Led Y position relative to the switch center
  led_rotation: 0 # Led rotation

  vertical_underglow_shift: -kx + 7.8 # How much to shift underglow leds tied to keys
  vertical_diode_shift: 1.5 # How much to shift to avoid overlap
  horizontal_diode_shift: -0.5 kco - 0.85

  diode_rotation: 0 # Diode rotation
  switch_rotation: 180 # Hotswap south, led north

  top_plate_thickness: 1.3
  internal_distance_to_top_plate: 2.2

  # Physical measures
  screw_radius: 1 + tolerance_small / 2 # M2 screws
  screw_diameter: screw_radius * 2
  screw_head_radius: 2.05
  screw_head_diameter: screw_head_radius * 2
  standoff_radius: 1.575 + tolerance_small / 2 # M2 standoffs https://keeb.io/products/m2-screws-and-standoffs
  standoff_diameter: standoff_radius * 2 # 3.15 + 0.2
  pwr_trace_width: 0.25 # 1A(0.25mm), 2A(0.8mm)
  gnd_trace_width: 0.25
  signal_trace_width: 0.15
  via_size: 0.56 # JLCPCB min 0.56 | KiCad default 0.8
  via_drill: 0.3 # JLCPCB min 0.3 | KiCad default 0.4

  case_wall_thickness: 0.5
  bottom_plate_thickness: 1.0
  internal_distance_to_bottom_plate: 4

  # mcu
  mcu_height: 33
  mcu_width: 18

anchors:
  - &mcu_anchor
    ref: main_inner_top
    shift: [-18.75, -13]

  - &thumb_anchor
    ref: main_inner_bottom
    shift: [-1.3kx, -1.8ky]
    rotate: 12

  - &display_connector_anchor
    ref: mcu_bottom_center
    shift: [0, -2.6/2]

  - &battery_connector_anchor
    ref: mcu_center
    shift: [-3, -27.2]

  - &power_switch_anchor
    ref: mcu_top_center
    shift: [-3.5, 0.5]

  - &reset_switch_anchor
    ref: power_switch
    shift: [9.5, 0.345]

points.zones:
  main:
    anchor:
      shift: [100, -100] # Fix KiCad placement
    key:
      tags:
        key: true
      origin: [-0.5kx, -0.5ky]

    columns:
      inner:
        key:
          column_net: C5
      index:
        key:
          column_net: C4
      middle:
        key:
          column_net: C3
          spread: kx + 4
          stagger: 0.45kx
      ring:
        key:
          column_net: C2
          spread: kx + 6
          stagger: -0.1kx
          splay: -2.5
      pinky:
        key:
          column_net: C1
          spread: kx + 4.5
          stagger: -0.55kx
          splay: -2.5
      outer:
        key:
          column_net: C0
          stagger: 0.5ky
          padding: 1.25ky
        rows:
          top:
            skip: true
          home:
            adjust:
              rotate: 90
          bottom:
            adjust:
              rotate: 90

    rows:
      bottom:
        row_net: R2
      home:
        row_net: R1
      top:
        row_net: R0

  thumb:
    anchor: *thumb_anchor
    key:
      tags: [key]
      rotate: 90
      origin: [-0.5kx, -0.5ky * 1.25]

    columns:
      outer:
        key:
          column_net: C5
      middle:
        key:
          column_net: C4
          stagger: 3
          splay: -3
      inner:
        key:
          column_net: C3
          stagger: 6
          splay: -12
          shift: [0.25, -2]

    rows:
      thome:
        row_net: R3

  # viewport fix
  svg_viewport_fix1:
    key.tags: [viewport_fix]
    anchor:
      ref: main_inner_top
      shift: [-45, 30]

  svg_viewport_fix2:
    key.tags: [viewport_fix]
    anchor:
      ref: main_inner_bottom
      shift: [-45, -55]

  # mcu
  mcu_center:
    key.tags: [helper]
    anchor: *mcu_anchor

  mcu_top_right:
    key.tags: [helper]
    anchor:
      ref: mcu_center
      shift: [mcu_width / 2, mcu_height / 2]

  mcu_top_left:
    key.tags: [helper]
    anchor:
      ref: mcu_center
      shift: [mcu_width / -2, mcu_height / 2]

  mcu_bottom_right:
    key.tags: [helper]
    anchor:
      ref: mcu_top_right
      shift: [0, -mcu_height]

  mcu_bottom_left:
    key.tags: [helper]
    anchor:
      ref: mcu_top_left
      shift: [0, -mcu_height]

  mcu_top_center:
    key.tags: [helper]
    anchor:
      aggregate:
        parts:
          - ref: mcu_top_left
          - ref: mcu_top_right

  mcu_bottom_center:
    key.tags: [helper]
    anchor:
      aggregate:
        parts:
          - ref: mcu_bottom_left
          - ref: mcu_bottom_right

  # connector
  display_connector:
    key.tags: [helper]
    anchor: *display_connector_anchor

  battery_connector:
    key.tags: [helper]
    anchor: *battery_connector_anchor

  # button
  power_switch:
    key.tags: [helper]
    anchor: *power_switch_anchor

  reset_switch:
    key.tags: [helper]
    anchor: *reset_switch_anchor

  # screw
  screw_mcu_cover_bottom_right:
    key.tags: [helper, screw, standoff]
    anchor:
      ref: mcu_bottom_center
      shift: [7, -7]

  screw_mcu_cover_bottom_left:
    key.tags: [helper, screw, standoff]
    anchor:
      ref: mcu_bottom_center
      shift: [-7, -7]

  screw_outer_thumb:
    key.tags: [helper, screw]
    anchor:
      ref: screw_mcu_cover_bottom_left
      shift: [0, -14]

  screw_mount_center:
    key.tags: [helper, screw]
    anchor:
      ref: main_middle_home
      shift: [11.95, -10]

  screw_mount_tr:
    key.tags: [helper, screw]
    anchor:
      ref: screw_mount_center
      shift: [22.5, 22.5]

  screw_mount_br:
    key.tags: [helper, screw]
    anchor:
      ref: screw_mount_center
      shift: [22.5, -22.5]

  screw_mount_tl:
    key.tags: [helper, screw]
    anchor:
      ref: screw_mount_center
      shift: [-22.5, 22.5]

  screw_mount_bl:
    key.tags: [helper, screw]
    anchor:
      ref: screw_mount_center
      shift: [-22.5, -22.5]

  # standoff
  standoff_middle_thumb:
    key.tags: [helper, screw, standoff]
    anchor:
      ref: thumb_middle_thome
      shift: [-2, 0.5kx + 0.7]

  standoff_lt:
    key.tags: [helper, standoff, screw]
    anchor:
      aggregate:
        parts:
          - ref: main_inner_top
          - ref: main_index_top
          - ref: main_inner_home
          - ref: main_index_home

  standoff_lb:
    key.tags: [helper, standoff, screw]
    anchor:
      aggregate:
        parts:
          - ref: main_inner_home
          - ref: main_index_home
          - ref: main_inner_bottom
          - ref: main_index_bottom

  standoff_rtr:
    key.tags: [helper, standoff, screw]
    anchor:
      - aggregate:
          parts:
            - ref: main_pinky_top
            - ref: main_pinky_home
        shift: [0.5kx - 0.55, 0]

  standoff_rbr:
    key.tags: [helper, standoff, screw]
    anchor:
      - aggregate:
          parts:
            - ref: main_pinky_home
            - ref: main_pinky_bottom
        shift: [0.5kx - 0.55, 0]

  standoff_rtl:
    key.tags: [helper, standoff, screw]
    anchor:
      aggregate:
        parts:
          - ref: main_pinky_top
          - ref: main_pinky_home
      shift: [-0.5kx + 0.55, 0]

  standoff_rbl:
    key.tags: [helper, standoff, screw]
    anchor:
      aggregate:
        parts:
          - ref: main_pinky_home
          - ref: main_pinky_bottom
      shift: [-0.5kx + 0.55, 0]

outlines:
  _viewport_fix:
    - what: rectangle
      where: [viewport_fix]
      size: 5

  _grid:
    - what: rectangle
      where: [/^main_(?!outer).*$/]
      size: [kx, ky]
      operation: stack
    - what: rectangle
      where: [/^(main_outer|thumb).*/]
      size: [1.25ky, kx]
      operation: stack

  _keycaps:
    # stem
    - what: rectangle
      where: [key]
      size: [10, 4]
      adjust:
        shift: [0, 0]
    - what: rectangle
      where: [key]
      size: [3.2, 4]
      adjust:
        shift: [0, -1.2]
    - what: circle
      where: [key]
      operation: stack
      radius: 1.6
    - what: rectangle
      where: [key]
      operation: stack
      size: [1.2, 3]
      adjust:
        shift: [-2.85, 0]
    - what: rectangle
      where: [key]
      operation: stack
      size: [1.2, 3]
      adjust:
        shift: [2.85, 0]
      # 1u
    - what: rectangle
      where: [/^main_(?!outer).*$/]
      operation: stack
      size: [kch, kcw]
      corner: 1.5
    - what: rectangle
      where: [/^main_(?!outer).*$/]
      operation: stack
      size: [kch - 2.5, kcw - 2.5]
      corner: 1
      # 1.25u
    - what: rectangle
      where: [/^(main_outer|thumb).*$/]
      operation: stack
      size: [kch, 1.25kcw]
      corner: 1.5
      adjust:
        rotate: -90
    - what: rectangle
      where: [/^(main_outer|thumb).*$/]
      operation: stack
      size: [kch - 2.5, 1.25kcw - 2.5]
      corner: 1
      adjust:
        rotate: -90

  _screws:
    - what: circle
      where: [screw]
      radius: screw_radius

  _screwheads:
    - what: circle
      where: [screw]
      radius: screw_head_radius
      operation: stack

  _standoffs:
    - what: circle
      where: [standoff]
      radius: standoff_radius
      operation: stack

  _switches:
    - what: rectangle
      where: [key]
      size: 15

  _switch_cutouts:
    - what: rectangle
      where: [key]
      size: kco

  _tentingpuck:
    - what: circle
      where: tp_center
      radius: 20.55

  _outline_shape_thumb_addon:
    - what: circle
      where: main_middle_home
      radius: 140
      adjust:
        shift: [-76.5, 72.5]
      operation: stack
    - what: rectangle
      where: main_inner_home
      size: [400, 250]
      adjust:
        shift: [0, 100]
      operation: subtract
    - what: rectangle
      where: main_inner_bottom
      size: [100, 100]
      adjust:
        shift: [-85, -35]
      operation: subtract

  _outline_shape_inner_curve:
    - what: circle
      where: main_middle_home
      radius: 44
      adjust:
        shift: [24.2, -82.8]
    - what: rectangle
      where: main_middle_bottom
      size: [20, 7]
      adjust:
        shift: [20, -18.65]
      operation: subtract

  _main_raw:
    - what: rectangle
      where: main_inner_home
      size: [180, 140]
      adjust:
        shift: [40, 39.25]
    - what: circle
      where: main_middle_home
      operation: intersect
      radius: 160
      adjust:
        shift: [2, -134.25]
    - +_outline_shape_thumb_addon
    - what: rectangle
      where: main_inner_top
      operation: add
      size: [20, 10]
      adjust:
        shift: [-19, 0.5kx - 10/2 - 1]
    - what: rectangle
      where: main_inner_home
      operation: subtract
      size: [40, 50]
      adjust:
        shift: [-48.3, 25]
    - what: rectangle
      where: main_inner_top
      operation: subtract
      size: [20, 10]
      adjust:
        shift: [-19.5, 0.5kx - 10/2 + 6]
    - what: circle
      where: main_inner_home
      operation: subtract
      radius: 200
      adjust:
        shift: [-228.25, 0]
    - what: rectangle
      where: thumb_outer_thome
      operation: subtract
      size: [60, 20]
      adjust:
        shift: [0, 20/2 + 0.5ky]
    - what: rectangle
      where: main_outer_home
      operation: subtract
      size: [115, 40]
      adjust:
        shift: [0, -40/2 - 0.5ky]

  _main_curve_inner_corner0:
    - what: rectangle
      where: main_middle_bottom
      size: [40, 20]
      adjust:
        rotate: 17
        shift: [8, -18]
    - what: outline
      name: _main_raw
      operation: intersect

  _main_curve_inner_corner1:
    - what: outline
      name: _main_curve_inner_corner0
      fillet: 15

  _main0:
    - what: outline
      name: _main_raw
      fillet: 1.5
    - what: outline
      name: _main_curve_inner_corner1

  _main:
    - what: outline
      name: _main0
      expand: 0.5

  _usb:
    - what: rectangle
      where:
        aggregate:
          parts:
            - ref: mcu_top_left
            - ref: mcu_top_right
      size: [12, 2]

  _mcu_raw:
    - what: rectangle
      where: mcu_center
      size: [18, 33]

  _mcu:
    - what: outline
      name: _mcu_raw
      fillet: 1.75

  _display:
    - what: rectangle
      where: display_connector
      operation: stack
      size: [14, 36]
      adjust:
        shift: [0, 36/2 - 1.3]
    - what: rectangle
      where: display_connector
      operation: stack
      size: [12, 38]
      adjust:
        shift: [0, 38/2 - 2 - 1.3]
    - what: rectangle
      where: display_connector
      operation: stack
      size: [12.820, 2.6]
      adjust:
        shift: [0, 0]
    - what: rectangle
      where: display_connector
      operation: stack
      size: [10.280, 2.6]
      adjust:
        shift: [0, -2]

  _debug_points:
    - what: rectangle
      where: true
      size: [3, 0.01]
      adjust:
        rotate: 45
    - what: rectangle
      where: true
      size: [0.01, 3]
      adjust:
        rotate: 45
      operation: stack
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [1.15, 1.15]

  _debug_points2:
    - what: circle
      where: true
      radius: 0.01

  pcb:
    - ^_main

  stuff:
    - ^_keycaps
    - ^_mcu
    #- ^_switches
    #- ^_screwheads

  debug_preview:
    - ^_viewport_fix
    - ^_debug_points
    - ^_grid
    - ^_main_raw
    - ^_mcu_raw
    #- ^_usb
    - ^_screws
    - ^_standoffs
    #- ^_screwheads
    - ^_switches
    - ^_switch_cutouts
    - ^_display

  preview:
    - ^_viewport_fix
    - ^_keycaps
    - ^_mcu
    #- ^_usb
    - ^_standoffs
    - ^_screwheads
    - ^_display
    - ^pcb
    #- ^_switches

pcbs:
  ouleetka:
    outlines:
      main:
        outline: pcb
    template: *kicad_template
    params:
      secret: 42
    footprints:
      key_switches_1u:
        what: *fp_key_switch
        where: [/^main_(?!(outer|inner)).*$/]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          side: "F"
          hotswap: true
          solder: false
          reversible: true
          choc_v2_support: false
          outer_pad_width_front: 2.6
          outer_pad_width_back: 2.6
          show_corner_marks: true
          show_keycaps: true
          keycaps_x: kcw
          keycaps_y: kch
        adjust:
          rotate: switch_rotation

      key_switches_1u_inner:
        what: *fp_key_switch
        where: [/^main_inner.*$/]
        params:
          from: "{{column_net}}"
          to: "{{colrow}}"
          side: "F"
          hotswap: true
          solder: false
          reversible: true
          choc_v2_support: false
          outer_pad_width_front: 2.6
          outer_pad_width_back: 1.9
          show_corner_marks: true
          show_keycaps: true
          keycaps_x: kcw
          keycaps_y: kch
        adjust:
          rotate: switch_rotation

      key_switches:
        what: *fp_key_switch
        where: [/^(main_outer|thumb).*$/]
        params:
          side: "F"
          from: "{{column_net}}"
          to: "{{colrow}}"
          hotswap: true
          solder: false
          reversible: true
          choc_v2_support: false
          outer_pad_width_front: 2.6
          outer_pad_width_back: 2.6
          show_corner_marks: true
          show_keycaps: true
          keycaps_x: 1.25kch
          keycaps_y: kcw
        adjust:
          rotate: switch_rotation

      mcu:
        what: *fp_mcu
        where: mcu_center
        adjust:
          shift: [0, 0.07]
        params:
          via_size: 0.8
          via_drill: 0.4
          only_required_jumpers: true
          use_rectangular_jumpers: false
          include_extra_pins: false
          include_traces: true

          designator: "MCU"
          side: "F"
          reversible: true
          reverse_mount: true
          show_silk_labels: false
          show_silk_labels_on_both_sides: false
          show_via_labels: false
          show_instructions: false
          P0: DAT
          P1: LED
          P21: C0
          P20: C1
          P19: C2
          P18: C3
          P15: C4
          P14: C5
          P2: SDA
          P3: SCL
          P4: CS
          P5: R0
          P6: R1
          P7: R2
          P8: R3

      key_diodes_front:
        what: *fp_diode
        where: [key]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          side: "F"
          reversible: false
          include_tht: false
        adjust:
          shift: [0, -2.385]
          rotate: 0

      key_diodes_back:
        what: *fp_diode
        where: [key]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          side: "B"
          reversible: false
          include_tht: false
        adjust:
          shift: [0, -2.385]
          rotate: 180

      display_header_niceview:
        what: *fp_display_niceview
        where: display_connector
        adjust:
          shift: [0, 16.710]
        params:
          reversible: true
          include_traces: true
          include_labels: false

      display_header_oled:
        what: *fp_display_oled
        where: display_connector
        adjust:
          shift: [0, 14.710]
        params:
          reversible: true
          include_traces: true
          invert_jumpers_position: true
          include_labels: false

      power_switch:
        what: *fp_power_switch
        where: power_switch
        params:
          reversible: true
          include_silkscreen: false
          include_courtyard: true
        adjust:
          rotate: 90

      reset_switch:
        what: *fp_reset_switch
        where: reset_switch
        params:
          reversible: true
          include_bosses: false
          include_courtyard: true

      battery_connector:
        what: *fp_battery_connector
        where: battery_connector
        params:
          reversible: true
          include_courtyard: true
          include_traces: true
          BAT_P: "BAT+"
        adjust:
          rotate: 90
